### ISSUE TITLE
Make gradebook more JSON-like readable

### ISSUE THREAD

**Issue by lgerhardt45** [oberrich/artemis_cli#13]
The gradebook (-template) should look more like this for negative/ positive feedbacks
```
 negative:
  - text: ''
    detail_text: ''
```

This makes it more readable.

**Comment by oberrich** [comment]
New gradebook format:
```yaml
{
  assignment: w01h01,
  assessments: [
  {
    name: ge36moy,
    score: 100,
    text: '',
    negative: [
      ['', ''],
      ['', '']
    ],
    positive: [
      ['', '']
    ]
  },
  # ...
  ]
}
```

**Comment by lgerhardt45** [comment]
Is there a reason for the positive/ negative feedbacks to not be a dict/ have the „text“, „detailed_text“ labels? Or just simplicity?

**Comment by oberrich** [comment]
Since the code of `artemis_cli grade` was reused feedbacks are implemented as lists that get mapped to dicts. Maybe I will change this once I properly implement this without reusing the code in a hacky manner.

**Comment by oberrich** [comment]
Changed gradebook layout once again to
```
generated_at: %s
assignment: %s
assessments:
  - name: %s
    score: 100
    text: ''
    negative:
      - text: '' 
        detail: ''
      - text: ''
        detail: ''
    positive:
      - text: ''
        detail: ''
  # %s
```
`% (utc.now, assignment, random penguin species)`

I agree that this is a lot more intuitive than the previous layout
